# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Tools.
# ------------------------------------------------------

#由vs转过来时 要手动进行配置
QT += core gui widgets multimedia

TEMPLATE = app
TARGET = Tetris
DESTDIR = ../x64/Debug
CONFIG += debug
LIBS += -L"."
DEPENDPATH += .
MOC_DIR += .
OBJECTS_DIR += debug
UI_DIR += .
RCC_DIR += .
HEADERS += ./Tetris.h
SOURCES += ./Tetris.cpp \
    ./main.cpp
FORMS += ./Tetris.ui
RESOURCES += Tetris.qrc
